-- Create scenario_breakthroughs table for storing winning paths from scenario injection
-- This table tracks the top-performing battles that successfully resolved specific objections

CREATE TABLE IF NOT EXISTS scenario_injections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  raw_objection TEXT NOT NULL,
  seller_persona_id UUID REFERENCES sandbox_personas(id) ON DELETE SET NULL,
  conflict_state TEXT NOT NULL, -- The structured conflict state generated by GPT-4o
  system_prompt TEXT NOT NULL, -- The full system prompt for this scenario
  status TEXT CHECK (status IN ('pending', 'running', 'completed', 'failed')) DEFAULT 'pending',
  total_sessions INTEGER DEFAULT 50,
  completed_sessions INTEGER DEFAULT 0,
  top_3_identified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Create scenario_breakthroughs table
CREATE TABLE IF NOT EXISTS scenario_breakthroughs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  scenario_injection_id UUID NOT NULL REFERENCES scenario_injections(id) ON DELETE CASCADE,
  battle_id UUID NOT NULL REFERENCES sandbox_battles(id) ON DELETE CASCADE,
  rank INTEGER CHECK (rank >= 1 AND rank <= 3), -- 1 = best, 2 = second, 3 = third
  referee_score INTEGER CHECK (referee_score >= 0 AND referee_score <= 100),
  conflict_resolved BOOLEAN DEFAULT FALSE, -- Did the seller's conflict state get resolved?
  price_maintained BOOLEAN DEFAULT FALSE, -- Did the closer maintain $82,700?
  winning_rebuttal TEXT NOT NULL,
  breakthrough_insight TEXT, -- Why this path worked
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_scenario_injections_status ON scenario_injections(status);
CREATE INDEX IF NOT EXISTS idx_scenario_injections_created_at ON scenario_injections(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_scenario_breakthroughs_scenario ON scenario_breakthroughs(scenario_injection_id);
CREATE INDEX IF NOT EXISTS idx_scenario_breakthroughs_rank ON scenario_breakthroughs(scenario_injection_id, rank);

-- Enable Row Level Security
ALTER TABLE scenario_injections ENABLE ROW LEVEL SECURITY;
ALTER TABLE scenario_breakthroughs ENABLE ROW LEVEL SECURITY;

-- Create policies: Allow service role to manage all records
CREATE POLICY "Service role can manage scenario_injections"
  ON scenario_injections
  FOR ALL
  USING (auth.role() = 'service_role');

CREATE POLICY "Service role can manage scenario_breakthroughs"
  ON scenario_breakthroughs
  FOR ALL
  USING (auth.role() = 'service_role');

-- Add comments
COMMENT ON TABLE scenario_injections IS 'Tracks scenario injection sessions where raw objections are transformed into structured personas';
COMMENT ON TABLE scenario_breakthroughs IS 'Stores the top 3 winning paths that successfully resolved specific objections while maintaining price';
